export * from './auth.service';
import { AuthService } from './auth.service';
export * from './categories.service';
import { CategoriesService } from './categories.service';
export * from './products.service';
import { ProductsService } from './products.service';
export * from './orders.service';
import { OrdersService } from './orders.service';
export * from './reviews.service';
import { ReviewsService } from './reviews.service';
export * from './messages.service';
import { MessagesService } from './messages.service';
export const APIS = [AuthService, CategoriesService, ProductsService, OrdersService, ReviewsService, MessagesService];
