export * from './auth.service';
import { AuthService } from './auth.service';
export * from './categories.service';
import { CategoriesService } from './categories.service';
export * from './favorites.service';
import { FavoritesService } from './favorites.service';
export * from './messages.service';
import { MessagesService } from './messages.service';
export * from './orders.service';
import { OrdersService } from './orders.service';
export * from './products.service';
import { ProductsService } from './products.service';
export * from './reviews.service';
import { ReviewsService } from './reviews.service';
export * from './uploads.service';
import { UploadsService } from './uploads.service';
export * from './users.service';
import { UsersService } from './users.service';
export const APIS = [AuthService, CategoriesService, FavoritesService, MessagesService, OrdersService, ProductsService, ReviewsService, UploadsService, UsersService];
