/**
 * MarketCore API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AuthTokenUser } from './authTokenUser';


export interface AuthToken { 
    access_token?: string;
    user?: AuthTokenUser;
}

