/**
 * MarketCore API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';
import { Message } from './message';
import { Product } from './product';


export interface Conversation { 
    id?: number;
    buyer_id?: number;
    seller_id?: number;
    product_id?: number;
    created_at?: string;
    product?: Product;
    buyer?: User;
    seller?: User;
    messages?: Array<Message>;
}

