/**
 * MarketCore API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';


export interface Message { 
    id?: number;
    conversation_id?: number;
    sender_id?: number;
    content?: string;
    is_read?: boolean;
    created_at?: string;
    sender?: User;
}

