/**
 * MarketCore API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Product } from './product';


export interface Order { 
    id?: number;
    buyer_id?: number;
    seller_id?: number;
    product_id?: number;
    total_amount?: number;
    status?: string;
    payment_gateway_id?: string;
    created_at?: string;
    product?: Product;
}

