/**
 * MarketCore API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProductCreate { 
    title: string;
    description: string;
    price: number;
    category_slug: string;
    /**
     * URL de la imagen
     */
    image_url?: string;
}

