/**
 * MarketCore API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProductsGet200ResponseMeta { 
    total?: number;
    page?: number;
    per_page?: number;
    pages?: number;
}

