/**
 * MarketCore API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';
import { ProductTrustSignals } from './productTrustSignals';


export interface Product { 
    id?: number;
    title?: string;
    description?: string;
    price?: number;
    category_slug?: string;
    is_sold?: boolean;
    image_url?: string;
    created_at?: string;
    seller?: User;
    trust_signals?: ProductTrustSignals;
}

