/**
 * MarketCore API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProductUpdate { 
    title?: string;
    description?: string;
    price?: number;
    category_slug?: string;
    image_url?: string;
    is_sold?: boolean;
}

