/**
 * MarketCore API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductSeller } from './productSeller';


export interface Product { 
    id?: number;
    title?: string;
    description?: string;
    price?: number;
    category_slug?: string;
    is_sold?: boolean;
    image_url?: string;
    created_at?: string;
    seller?: ProductSeller;
    trust_signals?: {
        average_rating?: number;
        total_sales?: number;
    };
}

