/**
 * MarketCore API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductsGet200ResponseMeta } from './productsGet200ResponseMeta';
import { Product } from './product';


export interface ProductsGet200Response { 
    products?: Array<Product>;
    meta?: ProductsGet200ResponseMeta;
}

