/**
 * MarketCore API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UploadsPost201Response { 
    message?: string;
    /**
     * URL pública de la imagen
     */
    url?: string;
}

