/**
 * MarketCore API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Review } from './review';


export interface UserReviewsResponse { 
    average_rating?: number;
    total_sales?: number;
    reviews?: Array<Review>;
}

