"""add favorites model

Revision ID: 0b5f95cacdaa
Revises: 7c5f3c0a9f21
Create Date: 2026-03-20 01:12:40.198116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b5f95cacdaa'
down_revision = '7c5f3c0a9f21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'product_id', name='uix_user_product_favorite')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_conversation_participants_product'), type_='unique')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_conversation_participants_product'), ['buyer_id', 'seller_id', 'product_id'], postgresql_nulls_not_distinct=False)

    op.drop_table('favorites')
    # ### end Alembic commands ###
