"""add user favorites

Revision ID: b923307045ee
Revises: e532324f8197
Create Date: 2026-03-18 15:59:33.337009

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b923307045ee"
down_revision = "e532324f8197"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_favorites",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "product_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_favorites")
    # ### end Alembic commands ###
